version: "3"
services:
    selenium:
        image: selenium/standalone-chrome:3.141.59-20200826
    ordure:
        build: .
        volumes:
            - .:/app
        environment:
            - REMOTE_SELENIUM=http://selenium:4444/wd/hub