name: CI

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: 5 4 * * *

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7
    - name: Get settings
      env:
        SETTINGS_BASE64: ${{ secrets.SETTINGS_SECRET_BASE64 }}
      run: |
        echo $SETTINGS_BASE64 | base64 --decode > settings.yaml
    - name: Install asdf
      uses: asdf-vm/actions/setup@v4
    - name: asdf cache
      id: asdf-cache
      uses: actions/cache@v5
      with:
        path: ~/.asdf/
        key: asdf-${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
    - name: Install CD tools from .tool-versions
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v4
    - name: Pyright
      run: make pyright
    - name: pre-commit
      run: make pre-commit
    - name: Run ordure
      run: docker compose up --build --exit-code-from ordure
    - name: Healthcheck
      run: curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${{ secrets.HC_PING_ID }}
